[package]
name = "client"
version = "0.1.0"
edition = "2024"
license.workspace = true
readme.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
sulfate_core = { path = "../sulfate_core" }
sysinfo = "0.39.6"
tokio = { version = "1.53.1", features = ["full"] }
xcap = "0.9.8"
